# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 80862d6f46f7bbe0bd20d00b3f67beac83f9d070a59d3176e0265b87a2b4c1ea50c7786bb6cc0e2d6aa309e0cef5ace3ebfd59593f8ac6a6ee4fbe947eec4ba7

test:
  secret_key_base: 2fbe0dbe2fe72051541caf7ddfaf89f547cdfc677b44ae2a880f55a9111e2d6cda0805d58e36221e0c55a5f56fdd2cd9bd69753811540d3f696311506b01df37

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
